### PR TITLE
fix rare animation bug

### LINKED ISSUE #21: rare animation bug
1) in board.powchess.com, set the drag duration to 2000ms.
2) take the white pawn on e2 and move it to e5 and keep holding it
3) release the mouse and try to catch the flying pawn on e4 or e3 (legal move)

### PR DESCRIPTION
**Pull request by CorteZzz137**
Closes #21

### CODE REVIEW

File: src/lib/draggable.ts [hunk 1]
```diff
@@ -172,6 +175,8 @@ export default function drag(node: HTMLDivElement, params: DragParams) {
 		globalDX += dx;
 		globalDY += dy;
 
+		// console.log(globalDX, globalDY);
+
```
Comment (trgsv) [inline src/lib/draggable.ts]: Remove comment

File: src/lib/Piece.svelte [hunk 2]
```diff
@@ -27,10 +27,13 @@
 	export let legalState: LegalState | undefined = undefined;
 	export let movableState: MovableState | undefined = undefined;
 
+	let pieceDiv: HTMLDivElement;
+
 	let selected = false;
 	let canDragVar = false;
 	let canSelectVar = false;
 	let canCaptureVar = false;
+	// let prevSquare = '';
```
Comment (trgsv) [inline src/lib/Piece.svelte]: remove comment

**Review by trgsv — APPROVED** [review]
